// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/ahmad-khatib0-org/megacommerce-proto/gen/go/user/v1"
	"github.com/ahmad-khatib0-org/megacommerce-user/internal/store"
	"github.com/ahmad-khatib0-org/megacommerce-user/pkg/models"
	"github.com/ahmad-khatib0-org/megacommerce-user/pkg/utils"
	mock "github.com/stretchr/testify/mock"
)

// NewMockUsersStore creates a new instance of MockUsersStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUsersStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUsersStore {
	mock := &MockUsersStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockUsersStore is an autogenerated mock type for the UsersStore type
type MockUsersStore struct {
	mock.Mock
}

type MockUsersStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUsersStore) EXPECT() *MockUsersStore_Expecter {
	return &MockUsersStore_Expecter{mock: &_m.Mock}
}

// SignupSupplier provides a mock function for the type MockUsersStore
func (_mock *MockUsersStore) SignupSupplier(ctx *models.Context, s *v1.User, token *utils.Token) *store.DBError {
	ret := _mock.Called(ctx, s, token)

	if len(ret) == 0 {
		panic("no return value specified for SignupSupplier")
	}

	var r0 *store.DBError
	if returnFunc, ok := ret.Get(0).(func(*models.Context, *v1.User, *utils.Token) *store.DBError); ok {
		r0 = returnFunc(ctx, s, token)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*store.DBError)
		}
	}
	return r0
}

// MockUsersStore_SignupSupplier_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SignupSupplier'
type MockUsersStore_SignupSupplier_Call struct {
	*mock.Call
}

// SignupSupplier is a helper method to define mock.On call
//   - ctx *models.Context
//   - s *v1.User
//   - token *utils.Token
func (_e *MockUsersStore_Expecter) SignupSupplier(ctx interface{}, s interface{}, token interface{}) *MockUsersStore_SignupSupplier_Call {
	return &MockUsersStore_SignupSupplier_Call{Call: _e.mock.On("SignupSupplier", ctx, s, token)}
}

func (_c *MockUsersStore_SignupSupplier_Call) Run(run func(ctx *models.Context, s *v1.User, token *utils.Token)) *MockUsersStore_SignupSupplier_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *models.Context
		if args[0] != nil {
			arg0 = args[0].(*models.Context)
		}
		var arg1 *v1.User
		if args[1] != nil {
			arg1 = args[1].(*v1.User)
		}
		var arg2 *utils.Token
		if args[2] != nil {
			arg2 = args[2].(*utils.Token)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockUsersStore_SignupSupplier_Call) Return(dBError *store.DBError) *MockUsersStore_SignupSupplier_Call {
	_c.Call.Return(dBError)
	return _c
}

func (_c *MockUsersStore_SignupSupplier_Call) RunAndReturn(run func(ctx *models.Context, s *v1.User, token *utils.Token) *store.DBError) *MockUsersStore_SignupSupplier_Call {
	_c.Call.Return(run)
	return _c
}
